cmake_minimum_required(VERSION 3.11)
project(faust VERSION 2.5)

set(PROJECT_INCLUDE ${PROJECT_SOURCE_DIR}/inc)
list(APPEND PROJECT_INCLUDE ${PROJECT_SOURCE_DIR}/core)
set(PROJECT_LIBS)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_FLAGS "-D__STDC_CONSTANT_MACROS")

if (MSVC)
    add_compile_options("/utf-8")
	add_compile_options("/EHsc")  # deal with MSVC Warning C4530
	add_compile_options("/Od")
    add_compile_options(/w44251 /w44275)
endif (MSVC)
find_package(Threads REQUIRED)

set(Machine super8 CACHE STRING "machine type")

if(UNIX)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
	set(FREETYPE_DIR "/usr/include/freetype2")
	message(STATUS "C Compiler Path: ${CMAKE_C_COMPILER}")
	message(STATUS "C++ Compiler Path: ${CMAKE_CXX_COMPILER}")
	if(${Machine} MATCHES "super4")
		message("linux machine use super4")
		set(CMAKE_INCLUDE_PATH "/usr/local/ffmpeg/include")
		set(CURL_INCLUDE_DIR "/home/coldJade/tools/curl/include")
		set(CMAKE_INCLUDE_PATH "/home/coldJade/tools/curl/include")
		set(CMAKE_LIBRARY_PATH "/usr/local/ffmpeg/lib")
		set(CMAKE_PREFIX_PATH "/home/coldJade/tools/curl/lib")
		set(CMAKE_LIBRARY_PATH "/home/coldJade/tools/jrtp/lib")
		set(LIBZ_INCLUDE_DIR "/home/coldJade/tools/zlib-1.2.11")
		set(CMAKE_PREFIX_PATH "/usr/local/cuda/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/ffmpeg/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/opencv/" ${CMAKE_PREFIX_PATH})
	elseif(${Machine} MATCHES "super8")
		message("linux machine use super8")
		set(CMAKE_PREFIX_PATH "/usr/local/cuda/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/ffmpeg/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/opencv/" ${CMAKE_PREFIX_PATH})
		set(WHISPER_LIB "/home/pangu/workspace/aesir/whispercpp/whisper.cpp-master/build/src/")
		set(GGML_LIB "/home/pangu/workspace/aesir/whispercpp/whisper.cpp-master/build/ggml/src/")
		set(CMAKE_C_COMPILER "/usr/local/gcc-10.5/bin/gcc")
		set(CMAKE_CXX_COMPILER "/usr/local/gcc-10.5/bin/g++")
		#message(STATUS "C Compiler Path: ${CMAKE_C_COMPILER}")
		#message(STATUS "C++ Compiler Path: ${CMAKE_CXX_COMPILER}")
	elseif(${Machine} MATCHES "super9")
		message("linux machine use super9")
		set(CMAKE_PREFIX_PATH "/usr/local/cuda/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/ffmpeg/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/opencv/" ${CMAKE_PREFIX_PATH})
		set(WHISPER_LIB "/home/blueFlower/workspace/aesir/whispercpp/whisper.cpp-master/build/src/")
		set(GGML_LIB "/home/blueFlower/workspace/aesir/whispercpp/whisper.cpp-master/build/ggml/src/")
	endif ()
endif ()

#find FFmpeg include and library file
set(FFMPEG_PATH "/usr/local/ffmpeg/" CACHE PATH "Custom path for find_path")
message("====== FIND FFMPEG LIBRARY AND INCLUDE ======")
find_path(FFMPEG_INCLUDE_DIR libavcodec/avcodec.h PATHS ${FFMPEG_PATH} REQUIRED)
list(APPEND PROJECT_INCLUDE ${FFMPEG_INCLUDE_DIR})
find_library(AVCODEC_LIBRARY avcodec REQUIRED)
list(APPEND PROJECT_LIBS ${AVCODEC_LIBRARY})
find_library(AVFORMAT_LIBRARY avformat)
list(APPEND PROJECT_LIBS ${AVFORMAT_LIBRARY})
find_library(AVUTIL_LIBRARY avutil)
list(APPEND PROJECT_LIBS ${AVUTIL_LIBRARY})
find_library(AVDEVICE_LIBRARY avdevice)
list(APPEND PROJECT_LIBS ${AVDEVICE_LIBRARY})
find_library(AVFILTER_LIBRARY avfilter)
list(APPEND PROJECT_LIBS ${AVFILTER_LIBRARY})
find_library(SWRESAMPLE_LIBRARY swresample)
list(APPEND PROJECT_LIBS ${SWRESAMPLE_LIBRARY})
find_library(SWSCALE_LIBRARY swscale)
list(APPEND PROJECT_LIBS ${SWSCALE_LIBRARY})
message(STATUS "ffmpeg include:${FFMPEG_INCLUDE_DIR}")
message(STATUS "avcodec lib:${AVCODEC_LIBRARY}")
message(STATUS "avformat lib:${AVFORMAT_LIBRARY}")
message(STATUS "avutil lib:${AVUTIL_LIBRARY}")
message(STATUS "avdevice lib:${AVDEVICE_LIBRARY}")
message(STATUS "avfilter lib:${AVFILTER_LIBRARY}")
message(STATUS "swresample lib:${SWRESAMPLE_LIBRARY}")
message(STATUS "swscale lib:${SWSCALE_LIBRARY}")

#find PJSIP include and library file
message("====== FIND PJSIP LIBRARY AND INCLUDE ======")
set(PJSIP_INCLUDE "/usr/local/pjsip/include")
file(GLOB PJSIP_LIBS "/usr/local/pjsip/lib/*.so")
list(APPEND PROJECT_INCLUDE ${PJSIP_INCLUDE})
list(APPEND PROJECT_LIBS ${PJSIP_LIBS})
message(STATUS "pjsip include: ${PJSIP_INCLUDE}")
message(STATUS "pjsip lib: ${PJSIP_LIBS}")

#find whisper library file
message("====== FIND WHISPER LIBRARY AND INCLUDE ======")
file(GLOB WHISPER_LIBS "${WHISPER_LIB}*.so")
file(GLOB GGML_LIBS "${GGML_LIB}libggml.so")
list(APPEND PROJECT_INCLUDE "${PROJECT_SOURCE_DIR}/inc/whisper/ggml/include")
list(APPEND PROJECT_LIBS ${WHISPER_LIBS})
list(APPEND PROJECT_LIBS ${GGML_LIBS})
message(STATUS "whisper lib: ${WHISPER_LIBS}")
message(STATUS "ggml lib: ${GGML_LIBS}")

#set(SHERPA_ONNX_ROOT "/usr/local/sherpa-onnx/build-shared/")
#include_directories(${SHERPA_ONNX_ROOT}/include)
#link_directories(${SHERPA_ONNX_ROOT}/lib)
#set(ONNXRUNTIME_DIR "/usr/local/onnxruntime-linux-x64-cuda-1.13.1")
#include_directories(${ONNXRUNTIME_DIR}/include)

include(${PROJECT_SOURCE_DIR}/inc/remix/remixlink.cmake)


add_subdirectory(src)
add_subdirectory(test/testSIP)