cmake_minimum_required(VERSION 3.11)
project(faust VERSION 0.0.3)

set(PROJECT_INCLUDE ${PROJECT_SOURCE_DIR}/inc)
list(APPEND PROJECT_INCLUDE ${PROJECT_SOURCE_DIR}/core)
set(PROJECT_LIBS)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_FLAGS "-D__STDC_CONSTANT_MACROS")

if (MSVC)
    add_compile_options("/utf-8")
	add_compile_options("/EHsc")  # deal with MSVC Warning C4530
	add_compile_options("/Od")
    add_compile_options(/w44251 /w44275)
endif (MSVC)
find_package(Threads REQUIRED)

set(Machine super9 CACHE STRING "machine type")
option(USE_X_MIX "use X team mix tool" OFF)
message("Machine is ${Machine}, use xteam mix tool is ${USE_X_MIX}")

if(UNIX)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
	set(FREETYPE_DIR "/usr/include/freetype2")
	if(${Machine} MATCHES "super4")
		message("linux machine use super4")
		set(CMAKE_INCLUDE_PATH "/usr/local/ffmpeg/include")
		set(CURL_INCLUDE_DIR "/home/coldJade/tools/curl/include")
		set(CMAKE_INCLUDE_PATH "/home/coldJade/tools/curl/include")
		set(CMAKE_LIBRARY_PATH "/usr/local/ffmpeg/lib")
		set(CMAKE_PREFIX_PATH "/home/coldJade/tools/curl/lib")
		set(CMAKE_LIBRARY_PATH "/home/coldJade/tools/jrtp/lib")
		set(LIBZ_INCLUDE_DIR "/home/coldJade/tools/zlib-1.2.11")
		set(CMAKE_PREFIX_PATH "/usr/local/cuda/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/ffmpeg/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/opencv/" ${CMAKE_PREFIX_PATH})
	elseif(${Machine} MATCHES "super8")
		message("linux machine use super8")
		#set(CMAKE_INCLUDE_PATH "/usr/local/ffmpeg/include")
		#set(CMAKE_LIBRARY_PATH "/usr/local/ffmpeg/lib")
		#set(CMAKE_LIBRARY_PATH "/usr/lib64")
		set(CMAKE_PREFIX_PATH "/usr/local/cuda/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/ffmpeg/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/opencv/" ${CMAKE_PREFIX_PATH})
	elseif(${Machine} MATCHES "super9")
		message("linux machine use super9")
		set(CMAKE_INCLUDE_PATH "/usr/local/ffmpeg/include")
		set(CMAKE_LIBRARY_PATH "/usr/local/ffmpeg/lib")
		set(CMAKE_LIBRARY_PATH "/home/blueFlower/workspace/tools/zlib-1.2.11/build")
		set(LIBZ_INCLUDE_DIR "/home/blueFlower/workspace/tools/zlib-1.2.11")
		set(CURL_INCLUDE_DIR "/home/blueFlower/workspace/tools/curl/include")
		set(CMAKE_PREFIX_PATH "/usr/local/cuda/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/ffmpeg/" ${CMAKE_PREFIX_PATH})
		set(CMAKE_PREFIX_PATH "/usr/local/opencv/" ${CMAKE_PREFIX_PATH})
	endif ()
endif ()

#find FFmpeg include and library file
set(FFMPEG_PATH "/usr/local/ffmpeg/" CACHE PATH "Custom path for find_path")
message("====== FIND FFMPEG LIBRARY AND INCLUDE ======")
find_path(FFMPEG_INCLUDE_DIR libavcodec/avcodec.h PATHS ${FFMPEG_PATH} REQUIRED)
list(APPEND PROJECT_INCLUDE ${FFMPEG_INCLUDE_DIR})
find_library(AVCODEC_LIBRARY avcodec REQUIRED)
list(APPEND PROJECT_LIBS ${AVCODEC_LIBRARY})
find_library(AVFORMAT_LIBRARY avformat)
list(APPEND PROJECT_LIBS ${AVFORMAT_LIBRARY})
find_library(AVUTIL_LIBRARY avutil)
list(APPEND PROJECT_LIBS ${AVUTIL_LIBRARY})
find_library(AVDEVICE_LIBRARY avdevice)
list(APPEND PROJECT_LIBS ${AVDEVICE_LIBRARY})
find_library(AVFILTER_LIBRARY avfilter)
list(APPEND PROJECT_LIBS ${AVFILTER_LIBRARY})
find_library(SWRESAMPLE_LIBRARY swresample)
list(APPEND PROJECT_LIBS ${SWRESAMPLE_LIBRARY})
find_library(SWSCALE_LIBRARY swscale)
list(APPEND PROJECT_LIBS ${SWSCALE_LIBRARY})
message(STATUS "ffmpeg include:${FFMPEG_INCLUDE_DIR}")
message(STATUS "avcodec lib:${AVCODEC_LIBRARY}")
message(STATUS "avformat lib:${AVFORMAT_LIBRARY}")
message(STATUS "avutil lib:${AVUTIL_LIBRARY}")
message(STATUS "avdevice lib:${AVDEVICE_LIBRARY}")
message(STATUS "avfilter lib:${AVFILTER_LIBRARY}")
message(STATUS "swresample lib:${SWRESAMPLE_LIBRARY}")
message(STATUS "swscale lib:${SWSCALE_LIBRARY}")

if(USE_X_MIX)
	include(${PROJECT_SOURCE_DIR}/inc/audioMix/audioMixlink.cmake)
else()
	include(${PROJECT_SOURCE_DIR}/inc/remix/remixlink.cmake)
endif()

find_library(FFT_LIBRARY fftw3)
list(APPEND PROJECT_LIBS ${FFT_LIBRARY})
message(STATUS "fft lib:${FFT_LIBRARY}")

add_subdirectory(src)