#pragma once


#ifndef SPDLOG_ACTIVE_LEVEL
//    #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
    #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
//  #define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
#endif  // !SPDLOG_ACTIVE_LEVEL

